apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet # https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/
# 对于具有N个副本的StatefulSet，当部署Pod时，将按顺序从{0..N-1}开始创建它们。删除是{N-1..0}
# 在将缩放操作应用于Pod之前，其所有前任必须是Running and Ready。在Pod终止之前，其所有后继者必须完全关闭。

# 给定Pod的存储必须由PersistentVolume Provisioner根据请求的存储类进行配置，或者由管理员预先配置。
# StatefulSets 目前要求 Headless Service 负责Pod的网络身份。您有责任创建此服务。
# 删除和/或缩放StatefulSet将不会删除与StatefulSet关联的卷。这样做是为了确保数据安全，这通常比自动清除所有相关的StatefulSet资源更有价值。
# 删除StatefulSet时，StatefulSets不提供对pod终止的任何保证。要在StatefulSet中实现pod的有序和正常终止，可以在删除之前将StatefulSet缩减为0。
metadata:
  name: web
spec: #TODO 待整理， 具体参数见:https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#statefulsetspec-v1-apps
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template: # 同 pod (内部结构见：https://github.com/zgfh/k8s-demo/blob/master/pod/pod.yaml)
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
