apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
imagePullSecrets: # 如果指定则在创建pod时会自动添加到pod.spec.imagePullSecrets
  - name: daocloud-io

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-serviceaccount
spec:
  serviceAccountName: nginx # ServiceAccount 的名称
  containers:
  - image: daocloud.io/daocloud/daolab:nginx
    name: nginx

